### ISSUE TITLE
Are you a symfony-bundle or a pimcore-bundle?

### ISSUE THREAD

**Issue by lukadschaak** [teamneusta/pimcore-translation-migration-bundle#8]
Just as reminder for myself

**Comment by jdreesen** [comment]
Well, currently it uses Pimcore stuff. Do you think we should separate it?

**Comment by lukadschaak** [comment]
Close.

Technically it is indeed a symfony-bundle. The bundle file uses only Symfony components and there is no pimcore needed to technically use this bundle.

On the other hand, it will only work with Pimcore, because the command uses Pimcore's PHP Code.

So it doesn't matter this much and i will simply close this.
